[project]
name = "arxiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "dotenv>=0.9.9",
    "feedparser>=6.0.11",
    "ollama>=0.5.1",
    "openai>=1.93.0",
    "typing>=3.10.0.0",
]
